### ISSUE TITLE
Compile css with Sass.

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#12]
Add the sass template files for bootstrap4, include the overrides in the sass files and compile with gulp or grunt, configure python.

**Comment by bsesic** [comment]
Der pull-request ist jetzt nicht mehr aktuell. Muss ich nochmal überarbeiten.

**Comment by PatriciaKaluza** [comment]
Das sollten wir uns wirklich mal genauer anschauen, so schieben wir das nur nach hinten. Und es macht ja schon Sinn.
