### ISSUE TITLE
compact memory search not matching fields

### ISSUE THREAD

**Issue by sarafischer** [judaicalink/judaicalink-labs#159]
It's not possible to search within the fields for language, journal title, publisher etc. Currently elasticsearch only matches the query to the text field.

**Comment by bsesic** [comment]
@sarafischer Can you give an example for a query?

**Comment by sarafischer** [comment]
for example: 'lang: eng'
-> in cm_search/views.py result() is not fieldmatching implemented at the moment (as in search/views.py)
