### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#168]

**Comment by sarafischer** [comment]
Web Home: https://web.judaicalink.org/
![grafik](https://user-images.githubusercontent.com/59728334/151764922-9833c196-8024-43a7-b10c-3b7bd76c6c70.png)
estimated total blocking time: 323.41ms

Labs Home: https://labs.judaicalink.org/
![grafik](https://user-images.githubusercontent.com/59728334/151767284-57ffbc4f-bf99-4085-a47d-700b32a5c52b.png)
estimated total blocking time: 502.24ms

Suche: https://labs.judaicalink.org/search/all_search_nav
![grafik](https://user-images.githubusercontent.com/59728334/151768791-ea48a6fc-4ffb-489a-8cf4-ada717e9861c.png)
estimated total blocking time: 504.84ms

Beispiele für JudaicaLink Search:

Beispiele für Compact Memory Search:

Beispiele für Compact Memory Entity Search:

Beispiele für Entity Pages:

Datasets:

News:

FAQ:

About:

Disclaimer:

Contact:

**Comment by sarafischer** [comment]
[profiling_performance.zip](https://github.com/judaicalink/judaicalink-labs/files/7971071/profiling_performance.zip)
[profiling_network_1.zip](https://github.com/judaicalink/judaicalink-labs/files/7971089/profiling_network_1.zip)
[profiling_network_2.zip](https://github.com/judaicalink/judaicalink-labs/files/7971098/profiling_network_2.zip)

**Comment by bsesic** [comment]
# Todos
* reduce image size
* image quality
* javascript size
* minify
* gzip
* image encoding
* CSS
* text compression

**Comment by bsesic** [comment]
Cache and compression works.
Check it out:
![image](https://user-images.githubusercontent.com/105399/159892732-2e162f70-b4ef-41fd-a145-fecad7eaf2d7.png)
