### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#172]

**Comment by bsesic** [comment]
Define keywords for search engines:

<meta name="keywords" content="HTML, CSS, JavaScript">
Define a description of your web page:

<meta name="description" content="Free Web tutorials">
Define the author of a page:

<meta name="author" content="John Doe">

https://www.w3schools.com/html/html_head.asp

**Comment by sarafischer** [comment]
django sitemap framework für entity pages nutzen

**Comment by sarafischer** [comment]
meta-tags für keywords und description werden generiert

**Comment by bsesic** [comment]
Das Ganze muss noch für Hugo und Pubby gemacht werden.

**Comment by bsesic** [comment]
Sitemaps done.

**Comment by bsesic** [comment]
See more: https://docs.djangoproject.com/en/4.0/ref/contrib/sitemaps/#example
