### ISSUE TITLE
Fork me on Github soll auf Erklärungsseite verweisen

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#30]
muss noch ReadMe verbessert werden
Status: SPÄTER, ABER FORK AUF PUBBY WEG

**Comment by bsesic** [comment]
Meinen wir damit die Readme oder das Wiki.

**Comment by kaiec** [comment]
Weder noch, ich hätte gesagt, da gibt es eine eigene Seite in Labs, die das Konzept als lokale Anwendung erklärt.

**Comment by bsesic** [comment]
[ReadTheDocs](https://judaicalink-labs.readthedocs.io)

**Comment by bsesic** [comment]
@sarafischer Can you add the link to readthedocs in the [deployment](https://github.com/judaicalink/judaicalink-labs/tree/deployment) branch?

**Comment by bsesic** [comment]
Add another one.
