### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by bsesic** [judaicalink/judaicalink-labs#49]

**Comment by bsesic** [comment]
Labs fertig, Hugo so halb und Pubby funktioniert nicht weil die Seitenabfrage irgendwie zu kompliziert ist.

**Comment by bsesic** [comment]
@sarafischer Can you check and see what error pages are missing, not working and where (labs, hugo, pubby)?

**Comment by sarafischer** [comment]
- hugo: no error pages
- pubby: no error pages
- labs: 404 & 500 templates present
@bsesic which error pages do we need?

**Comment by bsesic** [comment]
> Which branch (labs) do I have to check?/Are there any changes in beta concerning this matter that are missing in deployment?

deployment for now. We cherry pick into beta later.

**Comment by bsesic** [comment]
> * hugo: no error pages
> * pubby: no error pages
> * labs: 404 & 500 templates present
>   @bsesic which error pages do we need?

We need:
404
403
500
400

See the documentation for django (here)[https://docs.djangoproject.com/en/4.0/ref/views/].

**Comment by bsesic** [comment]
Information for [Hugo](https://moonbooth.com/hugo/custom-404/).

**Comment by bsesic** [comment]
@sarafischer  fixed in pubby.

**Comment by bsesic** [comment]
ErrorDocument 404 /404.html added to sites-available in Apache config.
