### ISSUE TITLE
Feature: provide clickable examples for different searches

### ISSUE THREAD

**Issue by PatriciaKaluza** [judaicalink/judaicalink-labs#5]
Allows to get random data as a result for the search, so users can get an overview of JudaicaLink very fast.

**Comment by sarafischer** [comment]
still relevant, if yes for which search (jl, cm, cm_entity)?

**Comment by bsesic** [comment]
We have examples in jl. We could have some for cm and cm_entitiy.

**Comment by sarafischer** [comment]
added examples to cm & cm entity search
